'use strict';
Object.assign(paths,{warning:'M12 3l10 18H2zM12 9v5M12 18h.01',check:'M5 12l4 4L19 6'});
const ft=(zh,en)=>state.language==='en-US'?en:zh;
let feedbackFocus=new Map(),feedbackHiddenSerial=-1,feedbackLastSerial=0,feedbackTerminate=null,feedbackExit=null,welcomeShown=false;
const feedbackDialogs=`<section id="feedbackPanel" class="feedback-panel" role="status" aria-live="polite" hidden><span id="feedbackIcon"></span><div class="feedback-copy"><strong id="feedbackTitle"></strong><p id="feedbackHelp"></p><details id="feedbackFailures"><summary id="feedbackFailureSummary"></summary><ul id="feedbackFailureList"></ul></details></div><div class="feedback-controls"><button class="btn" id="feedbackRetry" onclick="retryWebVisibility()"></button><button class="btn" id="feedbackUndo" onclick="undoWebVisibility()"></button><button class="close-btn" id="feedbackDismiss" onclick="dismissFeedback()" aria-label="关闭操作提示">×</button></div></section>
<dialog class="dialog pref-dialog feedback-dialog" id="feedbackPropertiesDialog" aria-labelledby="feedbackPropertiesTitle"><header class="dialogheader"><h2 id="feedbackPropertiesTitle"></h2><button class="close-btn" onclick="closeFeedbackDialog('feedbackPropertiesDialog')" aria-label="关闭">${icon('close')}</button></header><div class="dialogbody"><dl id="feedbackPropertiesRows" class="feedback-property-grid"></dl><p class="feedback-error" id="feedbackPropertiesError" role="alert" tabindex="-1"></p></div><footer class="dialogfooter"><button class="btn" id="feedbackCopyProperties" onclick="copyWebProperties()"></button><button class="btn primary" id="feedbackPropertiesClose" onclick="closeFeedbackDialog('feedbackPropertiesDialog')"></button></footer></dialog>
<dialog class="dialog pref-dialog feedback-dialog" id="feedbackTerminateDialog" aria-labelledby="feedbackTerminateTitle"><header class="dialogheader"><h2 id="feedbackTerminateTitle"></h2><button class="close-btn" onclick="closeFeedbackDialog('feedbackTerminateDialog')" aria-label="关闭">${icon('close')}</button></header><div class="dialogbody"><div class="feedback-program" id="feedbackTerminateProgram"></div><p id="feedbackTerminateHelp"></p><div class="feedback-alternative">${icon('hidden')}<div><strong id="feedbackAlternativeTitle"></strong><span id="feedbackAlternativeHelp"></span><button class="rowaction" id="feedbackHideInstead" onclick="hideInsteadOfTerminate()"></button></div></div><p class="feedback-error" id="feedbackTerminateError" role="alert" tabindex="-1"></p></div><footer class="dialogfooter"><button class="btn" id="feedbackTerminateCancel" onclick="closeFeedbackDialog('feedbackTerminateDialog')"></button><button class="btn danger" id="feedbackTerminateConfirm" onclick="confirmWebTerminate()"></button></footer></dialog>
<dialog class="dialog pref-dialog feedback-dialog" id="feedbackExitDialog" aria-labelledby="feedbackExitTitle"><header class="dialogheader"><h2 id="feedbackExitTitle"></h2></header><div class="dialogbody"><p id="feedbackExitHelp"></p><p class="feedback-error" id="feedbackExitError" role="alert" tabindex="-1"></p></div><footer class="dialogfooter"><button class="btn" id="feedbackExitCancel" onclick="closeFeedbackDialog('feedbackExitDialog')"></button><button class="btn danger" id="feedbackExitConfirm" onclick="confirmWebExit()"></button></footer></dialog>
<dialog class="dialog pref-dialog feedback-dialog" id="feedbackWelcomeDialog" aria-labelledby="feedbackWelcomeTitle"><div class="dialogbody"><div class="feedback-welcome-hero"><div class="logo">${icon('brand')}</div><h3 id="feedbackWelcomeTitle"></h3><p id="feedbackWelcomeSubtitle"></p></div><div class="feedback-steps" id="feedbackWelcomeSteps"></div><p class="feedback-error" id="feedbackWelcomeError" role="alert" tabindex="-1"></p></div><footer class="dialogfooter"><button class="btn" id="feedbackWelcomeSkip" onclick="dismissWebWelcome(false)"></button><button class="btn primary" id="feedbackWelcomeStart" onclick="dismissWebWelcome(true)"></button></footer></dialog>`;
document.body.insertAdjacentHTML('beforeend',feedbackDialogs);$('.top-actions').insertAdjacentHTML('afterbegin','<button class="btn" id="visibilityUndoButton" onclick="undoWebVisibility()" hidden></button>');$('.bottom').insertAdjacentHTML('beforeend','<button class="rowaction feedback-help-button" id="feedbackWelcomeHelp" onclick="openWebWelcome()"></button>');
function openFeedbackDialog(id){if(pending||state.busy)return;const d=$('#'+id);feedbackFocus.set(id,document.activeElement);if(!d.open)d.showModal();updateFeedbackBusy();const focus={feedbackTerminateDialog:'feedbackTerminateCancel',feedbackExitDialog:'feedbackExitCancel',feedbackPropertiesDialog:'feedbackPropertiesClose',feedbackWelcomeDialog:'feedbackWelcomeSkip'};$('#'+focus[id]).focus()}
function closeFeedbackDialog(id){if(!pending&&!state.busy)$('#'+id).close()}
for(const d of document.querySelectorAll('.feedback-dialog')){d.addEventListener('cancel',e=>{if(pending||state.busy)e.preventDefault();if(d.id==='feedbackWelcomeDialog'){e.preventDefault();dismissWebWelcome(false)}});d.addEventListener('close',()=>{const focus=feedbackFocus.get(d.id);if(focus?.isConnected)focus.focus({preventScroll:true})})}
async function showWebProperties(id){try{const data=await command('properties',{id});if(!data)return;setText($('#feedbackPropertiesTitle'),data.name+' · '+t('properties'));setHtml($('#feedbackPropertiesRows'),data.rows.map(r=>`<dt>${esc(r.Key)}</dt><dd>${esc(r.Value)}</dd>`).join(''));setText($('#feedbackCopyProperties'),ft('复制信息','Copy information'));setText($('#feedbackPropertiesClose'),ft('关闭','Close'));setText($('#feedbackPropertiesError'),'');openFeedbackDialog('feedbackPropertiesDialog')}catch(e){toast(e.message,true)}}
function copyWebProperties(){const rows=[...$('#feedbackPropertiesRows').children],value=rows.map((n,i)=>i%2?'':n.textContent+': '+rows[i+1].textContent).filter(Boolean).join('\n');navigator.clipboard.writeText(value).then(()=>toast(ft('程序属性已复制','Program information copied'))).catch(e=>{setText($('#feedbackPropertiesError'),ft('无法复制，请选择信息后复制。','Unable to copy. Select the information and copy it.'));$('#feedbackPropertiesError').focus()})}
async function openTerminate(id){if(pending||state.busy)return;try{const data=await command('terminatePrepare',{id});if(!data)return;feedbackTerminate=data;setText($('#feedbackTerminateTitle'),ft(`结束 ${data.name} 进程？`,`End ${data.name}?`));setHtml($('#feedbackTerminateProgram'),`<span class="appicon"><img src="${esc(data.image)}" alt=""></span><div><strong>${esc(data.name)}</strong><small>${esc(data.proc)} · PID ${data.pid}</small></div>`);$('#feedbackTerminateProgram .appicon').classList.toggle('monochrome',!!data.darkPlate);$('#feedbackTerminateProgram .appicon').classList.toggle('dark-glyph',!!data.lightPlate);setText($('#feedbackTerminateHelp'),ft(`这会关闭 ${data.name}，未保存的内容可能丢失。再次启动程序后，托盘图标才可能重新出现。`,`This closes ${data.name}. Unsaved work may be lost. Its tray icon may return when you start the application again.`));setText($('#feedbackAlternativeTitle'),ft('只是想整理托盘？','Tidying your tray?'));setText($('#feedbackAlternativeHelp'),ft('隐藏图标即可，软件会继续运行。','Hide the icon and keep the application running.'));setText($('#feedbackHideInstead'),ft('仅隐藏图标 →','Hide the icon instead →'));setText($('#feedbackTerminateCancel'),ft('取消','Cancel'));setText($('#feedbackTerminateConfirm'),ft('结束 '+data.name+' 进程','End '+data.name));setText($('#feedbackTerminateError'),'');openFeedbackDialog('feedbackTerminateDialog')}catch(e){toast(e.message,true)}}
async function confirmWebTerminate(){if(!feedbackTerminate||pending||state.busy)return;pending++;updateBusy();try{const result=await send('terminate',{id:feedbackTerminate.id,token:feedbackTerminate.token});$('#feedbackTerminateDialog').close();toast(result?.persistenceError?ft('程序已结束，但恢复记录保存未完成：','Application ended, but recovery records could not be saved: ')+result.persistenceError:ft('程序已结束','Application ended'),!!result?.persistenceError)}catch(e){setText($('#feedbackTerminateError'),e.message);$('#feedbackTerminateError').focus()}finally{pending--;updateBusy()}}
function hideInsteadOfTerminate(){const target=feedbackTerminate;if(!target||pending||state.busy)return;$('#feedbackTerminateDialog').close();command('change',{ids:[target.id],hidden:true})}
async function openWebExit(skipDraft=false){if(!skipDraft&&state.page==='settings'&&preferencesDirty()){await goPage('exit');return}if(pending||state.busy)return;const data=await command('exitPrepare');if(!data)return;feedbackExit=data;setText($('#feedbackExitTitle'),ft('退出 TrayPilot？','Exit TrayPilot?'));setText($('#feedbackExitHelp'),data.restore?ft('退出前会恢复本工具管理的普通图标和系统控件；如果恢复失败，将保留恢复记录并提示。','Managed application icons and system controls will be restored before exit. If restoration fails, recovery records are retained.'):ft('当前设置为“退出时不恢复图标”。图标可能保持隐藏，直到重新启动 TrayPilot、对应程序或任务栏。自动隐藏规则会保留。','Restore on exit is off. Icons may remain hidden until TrayPilot, the application or taskbar restarts. Auto-hide rules are kept.'));setText($('#feedbackExitCancel'),ft('取消','Cancel'));setText($('#feedbackExitConfirm'),ft('确认退出','Exit'));setText($('#feedbackExitError'),'');openFeedbackDialog('feedbackExitDialog')}
async function confirmWebExit(){if(!feedbackExit||pending||state.busy)return;pending++;updateBusy();try{await send('exitConfirm',{token:feedbackExit.token});$('#feedbackExitDialog').close()}catch(e){setText($('#feedbackExitError'),e.message);$('#feedbackExitError').focus()}finally{pending--;updateBusy()}}
function openWebWelcome(){setText($('#feedbackWelcomeTitle'),ft('让托盘，回归清爽','Make room in your tray'));setText($('#feedbackWelcomeSubtitle'),ft('三个步骤，让需要的图标留在眼前。','Three steps to keep the icons you need in sight.'));setHtml($('#feedbackWelcomeSteps'),[[ft('找到你的程序','Find your application'),ft('真实程序图标与路径，帮助你确认目标。','Real program icons and paths identify your target.')],[ft('隐藏图标，继续运行','Hide icons, keep applications running'),ft('隐藏不会关闭软件，随时可以恢复或撤销。','Hiding keeps software running. Restore or undo at any time.')],[ft('按需创建自动隐藏规则','Create auto-hide rules when needed'),ft('可以只管理一枚图标，也可以管理此程序全部图标。','Manage a single icon or every icon from a program.')]].map(([title,help],i)=>`<div class="feedback-step"><b>${i+1}</b><div><strong>${title}</strong><p>${help}</p></div></div>`).join(''));setText($('#feedbackWelcomeSkip'),ft('先看看','Look around'));setText($('#feedbackWelcomeStart'),ft('开始整理','Get started'));setText($('#feedbackWelcomeError'),'');openFeedbackDialog('feedbackWelcomeDialog')}
async function dismissWebWelcome(focusSearch){if(pending||state.busy)return;try{await send('welcomeDismiss');$('#feedbackWelcomeDialog').close();if(focusSearch){await goPage('icons');$('#search').focus()}}catch(e){setText($('#feedbackWelcomeError'),e.message);$('#feedbackWelcomeError').focus()}}
function dismissFeedback(){feedbackHiddenSerial=state.operation?.serial??0;$('#feedbackPanel').hidden=true}
function retryWebVisibility(){command('visibilityRetry')}
function undoWebVisibility(){command('visibilityUndo')}
function renderFeedback(){const op=state.operation||{};setText($('#feedbackWelcomeHelp'),ft('使用入门','Getting started'));setText($('#visibilityUndoButton'),ft('撤销上次操作','Undo last action'));$('#visibilityUndoButton').hidden=false;setText($('#feedbackRetry'),ft('重试未完成项','Retry failed'));setText($('#feedbackUndo'),ft('撤销已完成项','Undo completed'));setText($('#feedbackFailureSummary'),ft('查看未完成项目','View failed items'));const phase=op.phase||'idle';$('#feedbackPanel').classList.toggle('failed',phase==='failed');$('#feedbackPanel').classList.toggle('working',phase==='working');$('#feedbackPanel').hidden=!['working','failed'].includes(phase)||feedbackHiddenSerial===op.serial;setHtml($('#feedbackIcon'),icon(phase==='failed'?'warning':'refresh'));setText($('#feedbackTitle'),phase==='failed'?ft(`${op.total} 项操作：${op.completed} 项已完成，${op.failed.length} 项未完成`,`${op.completed} of ${op.total} completed; ${op.failed.length} failed`):ft(`正在更新 ${op.total} 个普通图标…`,`Updating ${op.total} application icons…`));setText($('#feedbackHelp'),phase==='failed'?ft('已完成项保持原样；重试只处理未完成项。','Completed items are kept. Retry only the failed items.'):ft('等待任务栏确认显示状态，软件会继续运行。','Waiting for taskbar confirmation. Applications keep running.'));$('#feedbackFailures').hidden=phase!=='failed';setHtml($('#feedbackFailureList'),(op.failed||[]).map(f=>`<li><strong>${esc(f.name)}</strong> · ${esc(f.error)}</li>`).join(''));$('#feedbackRetry').hidden=!op.canRetry;$('#feedbackUndo').hidden=!op.canUndo;$('#feedbackDismiss').hidden=phase==='working';
 if(op.serial!==feedbackLastSerial&&['done','undone'].includes(phase)){feedbackLastSerial=op.serial;toast(ft(phase==='undone'?'已撤销上次图标操作':`已完成 ${op.completed} 项操作，软件继续运行`,phase==='undone'?'Last icon action undone':`${op.completed} actions completed; applications keep running`))}
 if(state.welcome&&!welcomeShown&&state.page==='icons'&&!document.querySelector('dialog[open]')&&!pending&&!state.busy){welcomeShown=true;openWebWelcome()}updateFeedbackBusy()}
function updateFeedbackBusy(){const busy=state.busy||pending>0;document.querySelectorAll('.feedback-dialog button:not(#feedbackHideInstead),#feedbackPanel button,#feedbackWelcomeHelp').forEach(b=>setProperty(b,'disabled',busy));setProperty($('#visibilityUndoButton'),'disabled',busy||!state.operation?.canUndo);const alternative=$('#feedbackHideInstead');if(feedbackTerminate)setProperty(alternative,'disabled',busy||!apps.some(a=>a.id===feedbackTerminate.id))}
