// Windows Forms Keys: Shift=0x10000, Control=0x20000, Alt=0x40000.
let settingsDraft=null,settingsBaseline=null,settingsVersion=0,settingsTab='general',settingsSync=Promise.resolve(),settingsSyncCount=0,settingsOperationError='';
let preferenceHotkeyIndex=0,preferenceHotkeyValue=0,pendingSettingsDestination=null,queuedSettingsLeave=null;
const prefTabScroll=new Map(),prefDialogFocus=new Map();
Object.assign(paths,{keyboard:'M2 6h20v13H2zM5 9h.01M9 9h.01M13 9h.01M17 9h.01M5 12h.01M9 12h.01M13 12h.01M17 12h.01M7 16h10',language:'M3 3h18v18H3zM6 17l4-10 4 10M8 13h4M17 8h2M17 12h2',power:'M12 2v10M7 5a9 9 0 1 0 10 0',arrow:'M8 4l8 8-8 8',warning:'M12 3l10 18H2zM12 9v5M12 18h.01',external:'M14 3h7v7M21 3L10 14M10 3H3v18h18v-7'});
const prefWords={
 settings:['设置','Settings'],subtitle:['让 TrayPilot 按你的习惯工作。','Make TrayPilot work the way you do.'],general:['常规','General'],appearance:['外观与语言','Appearance & language'],shortcuts:['快捷键','Shortcuts'],
 saved:['设置已保存','Settings saved'],unsaved:['还有未保存的更改','Unsaved changes'],saving:['正在保存…','Saving…'],syncing:['正在同步预览…','Updating preview…'],
 startupSection:['启动与托盘','Startup & tray'],startup:['开机启动 TrayPilot','Start TrayPilot at sign-in'],startupHelp:['登录 Windows 后自动启动，在托盘安静运行。','Start automatically when you sign in to Windows.'],startupLoading:['正在读取开机启动状态…','Reading startup registration…'],startupFailed:['暂时无法读取启动项，其他设置仍可保存。','Startup registration is unavailable. Other preferences can still be saved.'],retry:['重新读取','Read again'],
 showTrayIcon:['显示 TrayPilot 托盘图标','Show the TrayPilot tray icon'],showTrayHelp:['在托盘保留入口，随时打开主界面。','Keep an entry in the tray to open the main window.'],behavior:['窗口与退出行为','Window & exit behavior'],closeToTray:['关闭窗口后继续在后台运行','Keep running after closing the window'],closeHelp:['关闭按钮只收起窗口；退出请使用托盘菜单。','The close button hides the window. Use Exit in the tray menu to quit.'],restoreOnExit:['退出时恢复已隐藏的图标','Restore hidden icons on exit'],restoreHelp:['作用于普通软件图标和系统控件；关机或注销也遵循此选择。','Apply to application and system icons, including shutdown or sign-out.'],
 generalNote:['设置只改变 TrayPilot 的行为，隐藏图标不会结束对应程序。','Preferences change TrayPilot behavior. Hiding icons keeps their applications running.'],behaviorPreview:['行为预览','Behavior preview'],login:['登录 Windows 时','When you sign in'],autoStart:['自动启动 TrayPilot','Start TrayPilot automatically'],manualStart:['由你手动启动','Start it manually'],closeWindow:['关闭主窗口时','When you close the window'],background:['收起窗口，继续在后台运行','Hide the window and keep running'],exit:['退出 TrayPilot','Exit TrayPilot'],quit:['退出 TrayPilot 时','When you quit TrayPilot'],restoreAll:['恢复已隐藏的普通图标与系统控件','Restore hidden application and system icons'],keepHidden:['保留当前图标状态','Keep current icon visibility'],access:['再次打开主界面','Open the main window again'],accessTray:['点击 TrayPilot 的托盘图标。','Click the TrayPilot tray icon.'],accessRelaunch:['再次运行程序即可唤回窗口。','Launch TrayPilot again to bring back its window.'],accessShortcut:['也可以使用已启用的主界面快捷键：','You can also use the enabled main-window shortcut:'],
 theme:['界面主题','Interface theme'],light:['浅色','Light'],dark:['深色','Dark'],system:['跟随系统','System'],themeHelp:['选择后即时预览，保存后成为正式偏好；取消会恢复原外观。','Preview immediately. Save to keep it, or cancel to restore the previous theme.'],language:['界面语言','Interface language'],languageLabel:['显示语言','Display language'],languageHelp:['保存后应用到整个界面。','Apply to the entire interface when saved.'],appearancePreview:['预览你的工作空间','Preview your workspace'],appearanceNote:['主题预览保留当前页面和滚动位置，可以放心切换。','Theme previews preserve your page and scroll position.'],languageNote:['语言选择保留在草稿中，保存后生效。','Language changes stay in your draft until you save.'],
 globalShortcuts:['全局快捷键','Global shortcuts'],mainAction:['打开主界面','Open the main window'],showAction:['显示所有图标','Show all icons'],hideAction:['隐藏规则命中','Hide matching icons'],mainHelp:['在任意程序中打开或唤回 TrayPilot。','Open or bring back TrayPilot from another application.'],showHelp:['暂停普通自动隐藏，清除系统隐藏选择，并恢复图标。','Pause application auto-hide, clear system hide preferences and show icons.'],hideHelp:['继续普通规则，清除本次暂时显示例外；不重建系统隐藏选择。','Resume application rules and clear temporary visibility exceptions. System hide preferences remain cleared.'],enabled:['已启用','Enabled'],disabled:['未启用','Disabled'],shortcutNote:['组合键至少包含 Ctrl 或 Alt，F12 不可用；保存时会验证系统占用。','Use Ctrl or Alt. F12 is unavailable. Saving checks for system conflicts.'],shortcutGuide:['顺手的快捷操作','Shortcuts that fit your workflow'],shortcutGuideHelp:['可直接按下组合键录制，也可以逐项选择修饰键与主按键。','Record a key combination or choose modifiers and a primary key.'],shortcutScope:['全局快捷键在 TrayPilot 运行时生效，不需要主窗口保持打开。','Global shortcuts work while TrayPilot is running, including when the window is hidden.'],
 errorTitle:['请检查以下设置','Check these preferences'],keyError:['请使用包含 Ctrl 或 Alt 的合法组合，并避免重复绑定。','Use a valid combination with Ctrl or Alt and avoid duplicate bindings.'],saveChanges:['保存更改','Save changes'],cancelChanges:['取消修改','Cancel changes'],dirtyHelp:['修改尚未应用，保存后生效。','Changes have not been applied. Save to apply them.'],cleanHelp:['修改设置后，点击保存应用。','Edit preferences and save to apply them.'],keepRunning:['隐藏图标不会结束对应程序','Hiding icons keeps applications running'],applyOnSave:['设置统一保存后生效','Preferences apply when saved'],
 editHotkey:['修改快捷键','Edit shortcut'],capture:['按下新的组合键','Press a new key combination'],captureHelp:['至少包含 Ctrl 或 Alt。Tab 切换焦点，Esc 取消。','Include Ctrl or Alt. Tab moves focus; Escape cancels.'],manualKey:['也可以手动选择','Or choose the keys'],mainKey:['主按键','Primary key'],useHotkey:['使用此快捷键','Use this shortcut'],cancel:['取消','Cancel'],close:['关闭','Close'],
 discardTitle:['还有未保存的更改','You have unsaved changes'],discardSubtitle:['离开前决定是否保留本次修改。','Decide what to do with your draft before leaving.'],discardHelp:['可以留在设置页保存更改，或放弃本次修改后继续。','Stay here to save your changes, or discard this draft and continue.'],discardContinue:['放弃并继续','Discard and continue'],stay:['留在此页','Stay here'],
 about:['关于与更新','About & updates'],aboutSubtitle:['了解 TrayPilot，保持你的工作空间井然有序。','Learn about TrayPilot and keep your workspace organized.'],applicationDescription:['轻巧的 Windows 托盘图标管理工具','A lightweight tray icon manager for Windows'],developer:['开发者','Developer'],platform:['适用平台','Platform'],license:['版权信息','Copyright'],help:['帮助与项目','Help & project'],project:['项目主页','Project home'],usage:['使用说明','Usage guide'],issues:['问题反馈','Report an issue'],releases:['发布记录','Release history'],credits:['系统图标兼容性实现参考了 Windhawk 社区的开源贡献。','System icon compatibility draws on contributions from the Windhawk community.'],diagnostics:['运行诊断信息','Runtime diagnostics'],copy:['复制诊断信息','Copy diagnostics'],copied:['诊断信息已复制','Diagnostics copied'],aboutGuide:['简单、可控的更新','Updates under your control'],aboutGuideHelp:['检查更新只在你点击按钮时进行。','Check for updates only when you click the button.'],updateNote:['发现新版本后前往发布页下载，不自动替换程序、安装或重启。','Download new versions from the release page. No automatic replacement, installation or restart.'],manualUpdates:['更新检查由你手动触发','Updates are checked manually'],
 idle:['尚未检查更新','Updates have not been checked'],checking:['正在检查更新…','Checking for updates…'],current:['当前已是最新版本','Your version is up to date'],new:['发现新版本','New version available'],noRelease:['暂无正式发布版本','No stable release is published'],failed:['更新检查失败','Update check failed'],timeout:['更新检查超时','Update check timed out'],check:['检查更新','Check for updates'],retryUpdate:['重试检查','Try again'],download:['前往发布页下载','Open release download'],updateHelp:['手动检查正式发布版本。','Check for a stable release manually.'],retryHelp:['请检查网络连接，稍后重试。','Check your connection and try again.']
};
const pt=k=>(prefWords[k]||[k,k])[state.language==='en-US'?1:0];
const preferenceComparable=p=>p&&JSON.stringify({...p,hotkeys:p.hotkeys.map(h=>({enabled:h.enabled,keys:h.keys}))});
const preferencesDirty=()=>!!settingsDraft&&preferenceComparable(settingsDraft)!==preferenceComparable(settingsBaseline);
const preferenceInvalid=()=>settingsDraft?.hotkeys.map((h,i)=>h.enabled&&(!validPreferenceKey(h.keys)||settingsDraft.hotkeys.some((o,j)=>i!==j&&o.enabled&&o.keys===h.keys))?i:-1).filter(i=>i>=0)||[];
function validPreferenceKey(keys){const key=keys&65535;return !!(keys&(131072|262144))&&key>0&&key<=254&&![16,17,18,91,92,123].includes(key)&&!(keys&~(65535|131072|65536|262144))}
function preferenceKeyName(code){if(code>=65&&code<=90)return String.fromCharCode(code);if(code>=48&&code<=57)return String.fromCharCode(code);if(code>=112&&code<=135)return 'F'+(code-111);return ({8:'Backspace',9:'Tab',13:'Enter',27:'Escape',32:'Space',33:'Page Up',34:'Page Down',35:'End',36:'Home',37:'Left',38:'Up',39:'Right',40:'Down',45:'Insert',46:'Delete',186:';',187:'=',188:',',189:'-',190:'.',191:'/',192:'`',219:'[',220:'\\',221:']',222:"'"})[code]||(code>=96&&code<=105?'Num '+(code-96):'VK '+code)}
function preferenceKeyText(keys){return [...(keys&131072?['Ctrl']:[]),...(keys&262144?['Alt']:[]),...(keys&65536?['Shift']:[]),preferenceKeyName(keys&65535)].join('+')}
function preferenceKeyHtml(h){return (h.text||preferenceKeyText(h.keys)).split('+').map(k=>'<kbd>'+esc(k.trim())+'</kbd>').join('<span>+</span>')}
function setSettingsTab(tab){if(!['general','appearance','shortcuts'].includes(tab)||state.settings?.saving)return;prefTabScroll.set(settingsTab,$('#prefSettingsBody').scrollTop);settingsTab=tab;renderPreferences();$('#prefSettingsBody').scrollTop=prefTabScroll.get(tab)||0}
function editPreference(key,value){if(!settingsDraft||state.settings?.saving||pending)return;settingsDraft[key]=value;settingsOperationError='';settingsVersion++;renderPreferences();syncPreferenceDraft()}
function editPreferenceHotkey(index,enabled,keys){if(!settingsDraft||state.settings?.saving||pending)return;settingsDraft.hotkeys[index]={enabled,keys,text:preferenceKeyText(keys)};settingsOperationError='';settingsVersion++;renderPreferences();syncPreferenceDraft()}
function syncPreferenceDraft(){
 settingsSyncCount++;updatePreferencesBusy();
 settingsSync=settingsSync.catch(()=>{}).then(async()=>{try{await send('settingsDraft',{value:structuredClone(settingsDraft),version:settingsVersion})}catch(e){settingsOperationError=e.message}finally{settingsSyncCount--;renderPreferences()}});
 return settingsSync;
}
async function preferencesRequest(action,data={}){if(pending||state.busy)throw Error(t('busy'));pending++;pendingAction=action;updateBusy();try{return await send(action,data)}finally{pending--;pendingAction='';updateBusy()}}
async function saveSettings(){
 if(!settingsDraft||state.settings?.saving||pending)return;await settingsSync;
 const invalid=preferenceInvalid();if(invalid.length){renderPreferences();$('#prefErrorSummary').focus();return}
 try{await preferencesRequest('settingsSave',{value:structuredClone(settingsDraft),version:settingsVersion});settingsOperationError='';renderPreferences();toast(pt('saved'))}catch(error){settingsOperationError=error.message;renderPreferences();$('#prefErrorSummary').focus()}
}
async function cancelSettings(){if(pending||state.settings?.saving)return;await settingsSync;try{await preferencesRequest('settingsCancel');settingsOperationError='';renderPreferences()}catch(error){settingsOperationError=error.message;renderPreferences()}}
async function retrySettingsStartup(){try{await send('settingsStartupRetry')}catch(e){toast(e.message,true)}}
async function goPage(page){if(state.page==='settings'&&preferencesDirty()&&page!=='settings'){pendingSettingsDestination=page;openPreferencesDialog('prefDiscardDialog');return}await settingsSync;if(page==='exit'){await openWebExit(true);return}await command('navigate',{page})}
function requestSettingsLeave(page){queuedSettingsLeave=page;updatePreferencesBusy()}
async function discardSettingsAndContinue(){const target=pendingSettingsDestination;try{await settingsSync;await preferencesRequest('settingsCancel');settingsOperationError='';$('#prefDiscardDialog').close();if(target==='exit')await openWebExit(true);else await command('navigate',{page:target})}catch(e){setText($('#prefDiscardError'),e.message);$('#prefDiscardError').focus()}}
function openPreferencesDialog(id){if(pending||state.settings?.saving)return;const dialog=$('#'+id);prefDialogFocus.set(id,document.activeElement);setText(dialog.querySelector('.error'),'');dialog.showModal();updatePreferencesBusy();(id==='prefDiscardDialog'?$('#prefStay'):$('#prefCapture')).focus()}
function closePreferencesDialog(id){if(!pending&&!state.settings?.saving)$('#'+id).close()}
function openPreferenceHotkey(index){if(!settingsDraft||pending||state.settings?.saving)return;preferenceHotkeyIndex=index;preferenceHotkeyValue=settingsDraft.hotkeys[index].keys;setText($('#prefHotkeyAction'),pt(['mainAction','showAction','hideAction'][index]));
 const select=$('#prefMainKey'),codes=[...Array.from({length:26},(_,i)=>65+i),...Array.from({length:10},(_,i)=>48+i),...Array.from({length:11},(_,i)=>112+i)],saved=preferenceHotkeyValue&65535;if(!codes.includes(saved))codes.push(saved);
 setHtml(select,codes.map(k=>'<option value="'+k+'">'+esc(preferenceKeyName(k))+'</option>').join(''));patchPreferenceHotkeyComposer();openPreferencesDialog('prefHotkeyDialog')}
function patchPreferenceHotkeyComposer(){setProperty($('#prefModCtrl'),'checked',!!(preferenceHotkeyValue&131072));setProperty($('#prefModAlt'),'checked',!!(preferenceHotkeyValue&262144));setProperty($('#prefModShift'),'checked',!!(preferenceHotkeyValue&65536));setProperty($('#prefMainKey'),'value',String(preferenceHotkeyValue&65535));setProperty($('#prefCapture'),'value',preferenceKeyText(preferenceHotkeyValue));setText($('#prefHotkeyError'),'')}
function composePreferenceHotkey(){preferenceHotkeyValue=Number($('#prefMainKey').value)|($('#prefModCtrl').checked?131072:0)|($('#prefModAlt').checked?262144:0)|($('#prefModShift').checked?65536:0);setProperty($('#prefCapture'),'value',preferenceKeyText(preferenceHotkeyValue));setText($('#prefHotkeyError'),'')}
function capturePreferenceKey(e){
 if(['Tab','Escape'].includes(e.key))return;e.preventDefault();if(['Control','Alt','Shift','Meta'].includes(e.key))return;
 let key=/^Key[A-Z]$/.test(e.code)?e.code.charCodeAt(3):/^Digit\d$/.test(e.code)?e.code.charCodeAt(5):/^F\d+$/.test(e.key)?111+Number(e.key.slice(1)):/^Numpad\d$/.test(e.code)?96+Number(e.code.slice(6)):({Backspace:8,Enter:13,Space:32,PageUp:33,PageDown:34,End:35,Home:36,ArrowLeft:37,ArrowUp:38,ArrowRight:39,ArrowDown:40,Insert:45,Delete:46,Semicolon:186,Equal:187,Comma:188,Minus:189,Period:190,Slash:191,Backquote:192,BracketLeft:219,Backslash:220,BracketRight:221,Quote:222,NumpadMultiply:106,NumpadAdd:107,NumpadSubtract:109,NumpadDecimal:110,NumpadDivide:111})[e.code];
 const value=(key||0)|(e.ctrlKey?131072:0)|(e.altKey?262144:0)|(e.shiftKey?65536:0);if(!validPreferenceKey(value)||e.metaKey){setText($('#prefHotkeyError'),pt('keyError'));return}preferenceHotkeyValue=value;if(![...$('#prefMainKey').options].some(o=>Number(o.value)===key)){const option=new Option(preferenceKeyName(key),String(key));$('#prefMainKey').add(option)}patchPreferenceHotkeyComposer();
}
function focusPreferenceError(index){setSettingsTab('shortcuts');$('#pref-key-edit-'+index).focus()}
function renderPreferences(){
 const model=state.settings;
 if(model){const startupUnchanged=!settingsDraft||settingsDraft.startup===settingsBaseline?.startup;settingsBaseline=structuredClone(model.baseline);if(!settingsDraft||model.version>=settingsVersion){settingsDraft=structuredClone(model.draft);settingsVersion=model.version}else if(startupUnchanged)settingsDraft.startup=settingsBaseline.startup}
 document.querySelectorAll('#settingsPage [data-pref-text],#aboutPage [data-pref-text],.pref-dialog [data-pref-text]').forEach(n=>setText(n,pt(n.dataset.prefText)));
 document.querySelectorAll('.pref-dialog .close-btn').forEach(n=>setAttr(n,'aria-label',pt('close')));
 const tabs=['general','appearance','shortcuts'];for(const tab of tabs){const selected=settingsTab===tab;const node=$('#pref-tab-'+tab);node.classList.toggle('active',selected);setAttr(node,'aria-selected',String(selected));setProperty(node,'tabIndex',selected?0:-1);setProperty($('#pref'+tab[0].toUpperCase()+tab.slice(1)),'hidden',!selected)}
 if(settingsDraft){
  for(const key of ['startup','showTrayIcon','closeToTray','restoreOnExit'])setAttr($('#pref-'+key),'aria-checked',String(settingsDraft[key]===true));
  setText($('#prefStartupHelp'),pt(model?.startupLoading&&settingsDraft.startup==null?'startupLoading':settingsDraft.startup==null?'startupFailed':'startupHelp'));setProperty($('#prefStartupRetry'),'hidden',!model?.startupError);
  setText($('#prefPreviewLogin'),pt(settingsDraft.startup==null?'startupLoading':settingsDraft.startup?'autoStart':'manualStart'));setText($('#prefPreviewClose'),pt(settingsDraft.closeToTray?'background':'exit'));setText($('#prefPreviewQuit'),pt(settingsDraft.restoreOnExit?'restoreAll':'keepHidden'));setText($('#prefPreviewAccess'),pt(settingsDraft.showTrayIcon?'accessTray':'accessRelaunch')+(settingsDraft.hotkeys[0].enabled?' '+pt('accessShortcut')+' '+settingsDraft.hotkeys[0].text:''));
  $('#settingsPage').querySelectorAll('[data-pref-theme]').forEach(n=>{const selected=n.dataset.prefTheme===settingsDraft.theme;n.classList.toggle('active',selected);setAttr(n,'aria-pressed',String(selected));setAttr(n,'aria-label',pt(n.dataset.prefTheme))});
  setHtml($('#prefLanguage'),(model?.languages||[]).map(l=>'<option value="'+esc(l.code)+'">'+esc(l.name)+'</option>').join(''));setProperty($('#prefLanguage'),'value',settingsDraft.language);
  const invalid=preferenceInvalid();settingsDraft.hotkeys.forEach((h,i)=>{const row=$('#pref-hotkey-'+i),label=pt(['mainAction','showAction','hideAction'][i]);setText(row.querySelector('strong'),label);setHtml(row.querySelector('.pref-keycombo'),preferenceKeyHtml(h));setAttr(row.querySelector('.pref-key-edit'),'aria-label',pt('editHotkey')+' · '+label);setAttr(row.querySelector('.pref-key-edit'),'aria-describedby','pref-key-help-'+i+' pref-key-error-'+i);setAttr(row.querySelector('.pref-key-edit'),'aria-invalid',String(invalid.includes(i)));const toggle=row.querySelector('.pref-switch');setAttr(toggle,'aria-checked',String(h.enabled));setAttr(toggle,'aria-label',label+' · '+pt('enabled'));setText(row.querySelector('.pref-hotkey-status'),pt(h.enabled?'enabled':'disabled'));setText(row.querySelector('.pref-key-help'),pt(['mainHelp','showHelp','hideHelp'][i]));setText(row.querySelector('.error'),invalid.includes(i)?pt('keyError'):'')});
  const error=settingsOperationError||model?.error||'';setProperty($('#prefErrorSummary'),'hidden',!error&&!invalid.length);setText($('#prefSaveError'),error);setHtml($('#prefErrorLinks'),invalid.map(i=>'<a href="#pref-key-edit-'+i+'" onclick="event.preventDefault();focusPreferenceError('+i+')">'+esc(pt(['mainAction','showAction','hideAction'][i]))+'</a>').join(''));
  setText($('#prefTopStatus'),pt(model?.saving?'saving':preferencesDirty()?'unsaved':'saved'));setText($('#prefDirtyLabel'),pt(model?.saving?'saving':preferencesDirty()?'dirtyHelp':'cleanHelp'));
 }
 const about=state.about||{updateState:'idle',version:''},status=about.updateState||'idle';setText($('#prefVersion'),about.version);setText($('#prefUpdateStatus'),pt(status)+(status==='new'?' · '+about.release:status==='current'?' · '+about.version:''));$('#prefUpdateStatus').classList.toggle('pref-update-error',['failed','timeout'].includes(status));setText($('#prefUpdateHelp'),pt(['failed','timeout'].includes(status)?'retryHelp':'updateHelp'));setText($('#prefCheckUpdate'),pt(status==='checking'?'checking':['failed','timeout'].includes(status)?'retryUpdate':'check'));setProperty($('#prefDownload'),'hidden',!about.download);setText($('#prefDiagnostics'),about.diagnostic||'');
 for(const theme of ['light','dark']){const button=$('#about-'+theme);setText(button,pt(theme));button.classList.toggle('active',state.theme===theme);setAttr(button,'aria-pressed',String(state.theme===theme));setAttr(button,'aria-label',pt(theme))}
 updatePreferencesBusy();
}
function updatePreferencesBusy(){
 const saving=!!state.settings?.saving||pending>0||state.busy;
 $('#settingsPage').querySelectorAll('button,select').forEach(n=>{let disabled=saving;if(['prefCancel','prefSave'].includes(n.id))disabled||=!preferencesDirty();if(n.id==='prefSave')disabled||=settingsSyncCount>0||!!state.settings?.startupLoading;if(n.id==='pref-startup')disabled||=settingsDraft?.startup==null||!!state.settings?.startupLoading;if(n.id==='prefStartupRetry')disabled||=!!state.settings?.startupLoading;setProperty(n,'disabled',disabled)});
 setText($('#prefSave'),pt(state.settings?.saving?'saving':'saveChanges'));setAttr($('#prefSettingsBody'),'aria-busy',String(!!state.settings?.saving));
 document.querySelectorAll('.pref-dialog button,.pref-dialog input,.pref-dialog select').forEach(n=>setProperty(n,'disabled',saving));
 setProperty($('#prefCheckUpdate'),'disabled',state.about?.updateState==='checking');setProperty($('#prefDownload'),'disabled',state.about?.updateState==='checking');
 if(queuedSettingsLeave&&!saving){pendingSettingsDestination=queuedSettingsLeave;queuedSettingsLeave=null;openPreferencesDialog('prefDiscardDialog')}
}
async function checkAboutUpdate(){try{await send('aboutCheck')}catch(e){toast(e.message,true)}}
async function openAboutLink(kind){try{await send('aboutLink',{kind})}catch(e){toast(e.message,true)}}
async function copyAboutDiagnostics(){try{await send('aboutCopy');toast(pt('copied'))}catch(e){toast(e.message,true)}}
for(let i=0;i<3;i++){const row=document.createElement('div');row.id='pref-hotkey-'+i;row.className='pref-hotkey-row';row.innerHTML='<div class="pref-hotkey-top"><div class="pref-row-copy"><strong></strong></div><button class="pref-key-edit" id="pref-key-edit-'+i+'"><span class="pref-keycombo"></span>'+icon('edit')+'</button><span class="pref-hotkey-status"></span><button class="pref-switch" role="switch"></button></div><p class="pref-key-help" id="pref-key-help-'+i+'"></p><p class="error" id="pref-key-error-'+i+'"></p>';row.querySelector('.pref-key-edit').onclick=()=>openPreferenceHotkey(i);row.querySelector('.pref-switch').onclick=()=>editPreferenceHotkey(i,!settingsDraft.hotkeys[i].enabled,settingsDraft.hotkeys[i].keys);$('#prefHotkeyRows').append(row)}
$('#prefCapture').onkeydown=capturePreferenceKey;
$('#prefHotkeyForm').onsubmit=e=>{e.preventDefault();if(!validPreferenceKey(preferenceHotkeyValue)){setText($('#prefHotkeyError'),pt('keyError'));$('#prefHotkeyError').focus();return}editPreferenceHotkey(preferenceHotkeyIndex,settingsDraft.hotkeys[preferenceHotkeyIndex].enabled,preferenceHotkeyValue);$('#prefHotkeyDialog').close()};
for(const id of ['prefHotkeyDialog','prefDiscardDialog']){const dialog=$('#'+id);dialog.addEventListener('cancel',e=>{if(pending||state.settings?.saving)e.preventDefault()});dialog.addEventListener('close',()=>{if(!dialog.open){const target=prefDialogFocus.get(id);if(target?.isConnected&&!target.closest('[hidden]'))target.focus({preventScroll:true})}})}
$('#settingsPage .pref-tabs').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const tabs=['general','appearance','shortcuts'],index=tabs.indexOf(settingsTab);setSettingsTab(e.key==='Home'?tabs[0]:e.key==='End'?tabs[2]:tabs[(index+(e.key==='ArrowRight'?1:2))%3]);$('#pref-tab-'+settingsTab).focus()});
document.querySelectorAll('#settingsPage [data-icon],#aboutPage [data-icon],.pref-dialog [data-icon]').forEach(n=>setHtml(n,icon(n.dataset.icon)));
renderPreferences();
