'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={brand:'M4 15l2 5h12l2-5M7 6v5M12 3v8M17 7v4',restore:'M3 5v5h5M3 10a9 9 0 1 1 2 8',pause:'M8 5v14M16 5v14',play:'M8 4l12 8-12 8z',search:'M21 21l-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',refresh:'M20 7V3l-3 3M20 6a9 9 0 0 0-15 2M4 17v4l3-3M4 18a9 9 0 0 0 15-2',eye:'M2 12s3-7 10-7 10 7 10 7-3 7-10 7S2 12 2 12M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0',hidden:'M3 3l18 18M9 5c7-2 13 7 13 7l-3 4M6 6l-4 6s3 7 10 7c2 0 4-1 5-2',next:'M9 5l7 7-7 7',prev:'M15 5l-7 7 7 7',monitor:'M3 4h18v12H3zM8 21h8M12 16v5',settings:'M4 7h16M4 17h16M8 4v6M16 14v6',info:'M12 8h.01M12 11v6M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0',exit:'M10 4H4v16h6M14 8l4 4-4 4M8 12h12',tray:'M4 5h16v14H4zM4 13h5l1 3h4l1-3h5'};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[n]||paths.info}"/></svg>`;
let state={entries:[],capacity:6,theme:'light',language:'zh-CN',busy:false,operation:{}},page=0,pending=0,sequence=0,groupPath='',exitToken='',signature='',presented=false,wheel=0,feedbackTimer,feedbackSerial=0,feedbackPhase='';const requests=new Map(),rows=new Map();
const tr=(zh,en)=>state.language==='en-US'?en:zh;
function text(n,v){if(n.textContent!==String(v))n.textContent=v}function html(n,v){if(n._html!==v){n.innerHTML=v;n._html=v}}function attr(n,k,v){if(n.getAttribute(k)!==String(v))n.setAttribute(k,v)}
function send(action,data={}){const requestId=String(++sequence);return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{requests.delete(requestId);reject(Error(tr('响应超时','Response timeout')))},30000);requests.set(requestId,{resolve,reject,timer});window.chrome.webview.postMessage({action,requestId,...data})})}
async function command(action,data={}){if(pending||state.busy)return;pending++;updateBusy();try{return await send(action,data)}catch(e){showFeedback(e.message);text($('#trayGroupError'),e.message);text($('#trayExitError'),e.message);throw e}finally{pending--;updateBusy()}}
function safe(action,data={}){command(action,data).catch(()=>{})}
function groups(){const query=$('#traySearch').value.trim().toLocaleLowerCase(),map=new Map();for(const a of state.entries){const key=a.path.toLocaleLowerCase();if(!map.has(key))map.set(key,[]);map.get(key).push(a)}return [...map.values()].filter(g=>g.some(a=>(a.name+' '+a.path+' '+a.tooltip).toLocaleLowerCase().includes(query))).sort((a,b)=>a[0].name.localeCompare(b[0].name,state.language))}
function status(g){return g.every(a=>a.hidden)?tr('已隐藏','Hidden'):g.some(a=>a.hidden)?tr('部分隐藏','Partly hidden'):tr('可见','Visible')}
function patchRow(row,g,child=false){const a=g[0],sig=JSON.stringify([g,state.language]);if(!row.children.length)row.innerHTML='<span class="appicon"><img alt=""></span><span class="popup-name"><strong></strong><small></small></span><span class="status"></span><i></i>';if(row._sig!==sig){row._sig=sig;const plate=row.querySelector('.appicon'),image=plate.querySelector('img');plate.classList.toggle('monochrome',!!a.darkPlate);plate.classList.toggle('dark-glyph',!!a.lightPlate);if(image&&image.getAttribute('src')!==a.image)image.src=a.image;text(row.querySelector('strong'),child?(a.tooltip||a.identity):a.name);const small=row.querySelector('small');small.hidden=g.length<2;text(small,g.length+' '+tr('枚图标','icons'));const badge=row.querySelector('.status');text(badge,status(g));badge.classList.toggle('shown',g.every(x=>!x.hidden));html(row.querySelector('i'),icon(g.length>1?'next':a.hidden?'hidden':'eye'));attr(row,'aria-label',(child?a.tooltip||a.identity:a.name)+' · '+status(g));row.title=a.path}row.onclick=()=>g.length>1?openGroup(g[0].path):safe('change',{ids:g.map(a=>a.id),hidden:!g.every(a=>a.hidden)})}
function render(){attr(document.documentElement,'data-theme',state.theme);attr(document.documentElement,'lang',state.language);html($('#trayLogo'),icon('brand'));text($('#trayHint'),tr('托盘快捷管理','Tray quick controls'));text($('#trayOpen'),tr('打开主界面','Open window'));html($('#trayRestore'),icon('restore')+tr('恢复普通图标','Restore managed'));html($('#trayPause'),icon(state.paused?'play':'pause')+tr(state.paused?'继续自动隐藏':'暂停自动隐藏',state.paused?'Resume auto-hide':'Pause auto-hide'));attr($('#trayPause'),'aria-pressed',state.paused);html($('#traySearchIcon'),icon('search'));$('#traySearch').placeholder=tr('搜索程序或路径…','Search programs or paths…');attr($('#traySearch'),'aria-label',tr('搜索程序或路径','Search programs or paths'));text($('#traySection'),tr('程序快捷控制','Quick controls'));html($('#trayRefresh'),icon('refresh')+tr('刷新','Refresh'));html($('#trayPrevious'),icon('prev'));html($('#trayNext'),icon('next'));attr($('#trayPrevious'),'aria-label',tr('上一页','Previous page'));attr($('#trayNext'),'aria-label',tr('下一页','Next page'));
 const result=groups(),pages=Math.max(1,Math.ceil(result.length/state.capacity));page=Math.max(0,Math.min(page,pages-1));text($('#trayPageLabel'),`${page+1} / ${pages} · ${result.length} ${tr('个程序','programs')}`);$('#trayPrevious').disabled=page===0;$('#trayNext').disabled=page+1>=pages;
 const container=$('#trayApps'),wanted=new Set(),active=document.activeElement,scroll=container.scrollTop;for(const g of result.slice(page*state.capacity,(page+1)*state.capacity)){const key=g[0].path.toLocaleLowerCase();wanted.add(key);let row=rows.get(key);if(!row){row=document.createElement('button');row.className='popup-app';rows.set(key,row)}patchRow(row,g);if(!row.isConnected)container.append(row)}for(const child of [...container.children])if(child.classList.contains('popup-app')&&!wanted.has([...rows].find(([,r])=>r===child)?.[0]))child.remove();if(result.length)container.querySelector('.tray-empty')?.remove();let cursor=container.firstElementChild;for(const g of result.slice(page*state.capacity,(page+1)*state.capacity)){const row=rows.get(g[0].path.toLocaleLowerCase());if(row===cursor)cursor=cursor.nextElementSibling;else container.insertBefore(row,cursor)}for(const key of [...rows.keys()])if(!state.entries.some(a=>a.path.toLocaleLowerCase()===key))rows.delete(key);
 if(!result.length)html(container,`<div class="tray-empty">${icon('tray')}<strong>${tr('没有匹配的程序','No matching programs')}</strong><p>${tr('尝试清空搜索或刷新列表；系统控件请到系统图标管理。','Clear search or refresh. Manage system controls under System icons.')}</p></div>`);else container._html='';container.scrollTop=scroll;if(active?.isConnected&&document.activeElement!==active)active.focus({preventScroll:true});
 text($('#trayStartupLabel'),tr('开机启动','Start with Windows'));text($('#traySelfLabel'),tr('显示 TrayPilot 托盘图标','Show TrayPilot tray icon'));attr($('#trayStartup'),'aria-label',tr('开机启动','Start with Windows'));attr($('#traySelf'),'aria-label',tr('显示 TrayPilot 托盘图标','Show TrayPilot tray icon'));attr($('#trayStartup'),'aria-checked',state.startup===true);attr($('#traySelf'),'aria-checked',state.showTray);$('#trayStartup').title=state.startupError||'';
 for(const [id,name,zh,en] of [['traySystem','monitor','系统图标','System'],['traySettings','settings','设置','Settings'],['trayAbout','info','关于','About'],['trayExit','exit','退出','Exit']])html($('#'+id),icon(name)+tr(zh,en));text($('#trayRetry'),tr('重试未完成项','Retry failed'));text($('#trayUndo'),tr('撤销','Undo'));
 const op=state.operation||{};if(op.serial!==feedbackSerial||op.phase!==feedbackPhase||op.phase==='working'){feedbackSerial=op.serial;feedbackPhase=op.phase;if(op.phase==='working')showFeedback(tr(`正在处理 ${op.total} 枚图标…`, `Updating ${op.total} icons…`),false);else if(op.phase==='failed')showFeedback(tr(`${op.total} 项操作：${op.completed} 项完成，${op.failed.length} 项未完成`,`${op.completed} of ${op.total} completed; ${op.failed.length} failed`),false);else if(['done','undone'].includes(op.phase))showFeedback(tr(op.phase==='undone'?'已撤销上次操作':`已完成 ${op.completed} 项操作，软件继续运行`,op.phase==='undone'?'Last action undone':`${op.completed} actions completed; applications keep running`))}$('#trayRetry').hidden=!op.canRetry;$('#trayUndo').hidden=!op.canUndo;renderGroup();updateBusy();
 if(!presented){presented=true;const images=[...document.images].filter(i=>i.getBoundingClientRect().width);Promise.race([Promise.allSettled(images.map(i=>i.decode())),new Promise(resolve=>setTimeout(resolve,100))]).then(()=>{let done=false;const ready=()=>{if(done)return;done=true;window.chrome.webview.postMessage({action:'presented'})};if(document.hidden)ready();else{requestAnimationFrame(ready);setTimeout(ready,100)}})}}
function showFeedback(message,timeout=true){text($('#trayFeedbackText'),message);$('#trayFeedback').hidden=false;clearTimeout(feedbackTimer);if(timeout)feedbackTimer=setTimeout(()=>$('#trayFeedback').hidden=true,6500)}
function updateBusy(){const busy=state.busy||pending>0;document.querySelectorAll('button').forEach(b=>b.disabled=busy);$('#trayStartup').disabled=busy||typeof state.startup!=='boolean';const pages=Math.max(1,Math.ceil(groups().length/state.capacity));$('#trayPrevious').disabled=busy||page===0;$('#trayNext').disabled=busy||page+1>=pages;attr($('#trayApps'),'aria-busy',busy)}
function movePage(delta){if(pending||state.busy||document.querySelector('dialog[open]'))return;const pages=Math.max(1,Math.ceil(groups().length/state.capacity)),next=Math.max(0,Math.min(page+delta,pages-1));if(page===next)return;page=next;render()}
function openGroup(path){groupPath=path;text($('#trayGroupError'),'');renderGroup();$('#trayGroupDialog').showModal();$('#trayGroupClose').focus()}
function renderGroup(){if(!groupPath)return;const g=state.entries.filter(a=>a.path.toLocaleLowerCase()===groupPath.toLocaleLowerCase());if(!g.length){if($('#trayGroupDialog').open)$('#trayGroupDialog').close();return}text($('#trayGroupTitle'),g[0].name);text($('#trayGroupHelp'),tr('可分别管理同一程序的图标，软件继续运行。','Manage each program icon separately; keep the application running.'));const host=$('#trayGroupEntries'),wanted=new Set(g.map(a=>a.id)),active=document.activeElement,scroll=host.scrollTop;for(const row of [...host.children])if(!wanted.has(row.dataset.id))row.remove();let cursor=host.firstElementChild;for(const a of g){let row=[...host.children].find(r=>r.dataset.id===a.id);if(!row){row=document.createElement('button');row.className='popup-app';row.dataset.id=a.id}patchRow(row,[a],true);if(row===cursor)cursor=cursor.nextElementSibling;else host.insertBefore(row,cursor)}host.scrollTop=scroll;if(active?.isConnected&&document.activeElement!==active)active.focus({preventScroll:true});html($('#trayGroupAll'),icon(g.every(a=>a.hidden)?'eye':'hidden')+tr(g.every(a=>a.hidden)?'恢复此程序全部图标':'隐藏此程序全部图标',g.every(a=>a.hidden)?'Show all program icons':'Hide all program icons'));$('#trayGroupAll').onclick=()=>safe('change',{ids:g.map(a=>a.id),hidden:!g.every(a=>a.hidden)})}
async function openExit(){try{const data=await command('exitPrepare');if(!data)return;exitToken=data.token;text($('#trayExitTitle'),tr('退出 TrayPilot？','Exit TrayPilot?'));text($('#trayExitHelp'),data.restore?tr('退出前恢复本工具管理的图标；恢复失败会保留记录并提示。','Restore managed icons before exiting. Failed restoration keeps its recovery records.'):tr('当前设置为退出时不恢复图标。图标可能保持隐藏，直到重新启动 TrayPilot、程序或任务栏。','Restore on exit is off. Icons may remain hidden until TrayPilot, the program or taskbar restarts.'));text($('#trayExitCancel'),tr('取消','Cancel'));text($('#trayExitConfirm'),tr('确认退出','Exit'));text($('#trayExitError'),'');$('#trayExitDialog').showModal();$('#trayExitCancel').focus()}catch(e){if(e.message.includes('设置页')||e.message.includes('draft'))safe('navigate',{page:'settings'})}}
$('#trayOpen').onclick=()=>safe('trayOpen');$('#trayRestore').onclick=()=>safe('restore');$('#trayPause').onclick=()=>safe('rulePause',{value:!state.paused});$('#trayRefresh').onclick=()=>safe('refresh');$('#traySearch').oninput=()=>{page=0;render()};$('#trayPrevious').onclick=()=>movePage(-1);$('#trayNext').onclick=()=>movePage(1);$('#trayStartup').onclick=()=>safe('trayStartup',{value:!state.startup});$('#traySelf').onclick=()=>safe('traySelf',{value:!state.showTray});$('#traySystem').onclick=()=>safe('navigate',{page:'system'});$('#traySettings').onclick=()=>safe('navigate',{page:'settings'});$('#trayAbout').onclick=()=>safe('navigate',{page:'about'});$('#trayExit').onclick=openExit;$('#trayUndo').onclick=()=>safe('visibilityUndo');$('#trayRetry').onclick=()=>safe('visibilityRetry');$('#trayGroupClose').onclick=()=>$('#trayGroupDialog').close();$('#trayExitCancel').onclick=()=>$('#trayExitDialog').close();$('#trayExitConfirm').onclick=()=>safe('exitConfirm',{token:exitToken});
document.addEventListener('wheel',e=>{if(e.target.closest?.('dialog')||document.querySelector('dialog[open]'))return;wheel+=e.deltaY;if(Math.abs(wheel)>=100){movePage(wheel>0?1:-1);wheel=0}e.preventDefault()},{passive:false});document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]'))return;if(e.key==='Escape'){e.preventDefault();safe('trayClose')}if(e.target.tagName!=='INPUT'&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();movePage(e.key==='ArrowRight'?1:-1)}});
window.chrome.webview.addEventListener('message',e=>{const message=e.data;if(message.type==='state'){const next=JSON.stringify(message);if(next===signature)return;signature=next;state=message;render()}else if(message.type==='result'){const request=requests.get(message.requestId);if(!request)return;requests.delete(message.requestId);clearTimeout(request.timer);message.success?request.resolve(message.data):request.reject(Error(message.error))}});window.chrome.webview.postMessage({action:'ready'});
